### ISSUE TITLE
Some videos are not unavailable.

### ISSUE THREAD

**Issue by MaFuyan** [hugojair/mocca-at-icmi21#1]
Some videos are not unavailable because the uploaders have closed their YouTube accounts.

**Comment by MaFuyan** [comment]
To be extract, this video https://www.youtube.com/watch?v=kCppUtS9vLk is unavailable.

**Comment by hugojair** [comment]
Thanks for Noticing this MaFuyan,

No worries, we anticipated this could happen, but please note that
nobody will have access to them so,it is ok.

Thanks again,

Best

HJ

**Comment by MaFuyan** [comment]
You are right. 

I will reopen this issue if I have any question about the data.

Thanks for your kindness.
