### ISSUE TITLE
A lot of videos aren't getting downloaded.

### ISSUE THREAD

**Issue by nikhilbyte** [hugojair/mocca-at-icmi21#2]
![Screenshot from 2021-05-10 06-17-39](https://user-images.githubusercontent.com/62005061/117593006-4eab0000-b158-11eb-878c-9215f73f7182.png)

**Comment by hugojair** [comment]
Hi

Can you please check your connection. Other  participants have successfully
downloaded all but 2 videos (these videos were removed by their authors(

Best
HJ

**Comment by nikhilbyte** [comment]
If anyone else struggles with this, I managed to download all but 2 videos by updating pytube.
