### ISSUE TITLE
Where can i find binary_detection_metadata.csv ?

### ISSUE THREAD

**Issue by nikhilbyte** [hugojair/mocca-at-icmi21#3]

**Comment by hugojair** [comment]
Hi, we are updating the repository with correct filenames and additional info. apologies for this confusion.

**Comment by nikhilbyte** [comment]
Hello hugojair, can I know when it'll be updated?

**Comment by hugojair** [comment]
Hi, I just updated the readme file for this specific issue, there was a mistake in the readme on the naming of files "binary_detection_metadata.csv", it should be: "Dataset_ComicMischief_Training_Scene_Binary_Annotations.csv"
